### ISSUE TITLE
Contributing guide for external contributors?

### ISSUE THREAD

**Issue by Nezteb** [serra-allgood/thurim#4]
Hello!

I'd like to assist with this project if possible. There are no open issues or contributing guidelines, so I figured I'd ask: how can folks help? 😄

**Comment by serra-allgood** [comment]
That's an excellent question! It never ceases to amaze me that people are interested in this project. I'll update the README with some contributing guidelines and see about practicing some project management chops by outlining where people can help in issues.

And sorry for taking so long to respond!

**Comment by serra-allgood** [comment]
See #5 for suggested guidelines. Is that enough to get you started, @Nezteb?

**Comment by Nezteb** [comment]
That's a great starting point, yes, thank you!

Whether or not I find the time to contribute, I do not know this year, but we shall see. 😄
